version: '2'
services:
  # Serviço para executar o postgresql
  consorcio.db:
    image: postgres:latest
    container_name: consorcio-db
    environment:
      - POSTGRES_DB=consorcio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432